### ISSUE TITLE
Where are these files?Please help me

### ISSUE THREAD

**Issue by Russell565** [zhouyuchong/face-recognition-deepstream#1]
Hello !
    I want to do face recognition by DS python. I have build DS-python ,created yolov5 , retina-face and arc face trt engine just like you said
    But,where are these files in the config txt？
    

1. `../../models/retinaface/nvdsinfer_customparser/libnvdsinfer_custom_impl_retinaface.so` in config_retinaface.txt
2. ` ../../models/yolov5/yolov5s/nvdsinfer_custom_impl_Yolo/libnvdsinfer_custom_impl_Yolo.so` in config_yolov5.txt
3. and your test file, i don't have this file `file:///opt/nvidia/deepstream/deepstream-6.0/sources/pythonapps/videos/samplevideo.h264`

Can you provide me with more information for reference? Pleas help me, thank you

**Comment by mrscarletzhou** [comment]
For the custom parser file, u can find it by the links in the README.[here](https://drive.google.com/drive/folders/1Ex48Jc3mzvQxhd4F9JvzEURnU3qu-Nu4)

For the test file, any video file is OK. Just download one. The only thing u should notice is the format of the file.
