### ISSUE TITLE
Can you please share the .wts for the arcface?

### ISSUE THREAD

**Issue by sbmalik** [zhouyuchong/face-recognition-deepstream#11]
I am trying to reproduce exactly your new updated code for face recognition, but the problem is insight-face has been updated a lot from that time. Your model on GDrive was generated on **CUDA COMPATIBILITY** is **7_5**. It will be a great help if you can share the `.wts` file so I can generate it on my **CUDA_8_6**.

**Comment by sbmalik** [comment]
Solved, converted it successfully after doing some updates.

**Comment by dungx48** [comment]
> I am trying to reproduce exactly your new updated code for face recognition, but the problem is insight-face has been updated a lot from that time. Your model on GDrive was generated on **CUDA COMPATIBILITY** is **7_5**. It will be a great help if you can share the `.wts` file so I can generate it on my **CUDA_8_6**.

Can you explain more? I am having the same problem as you

**Comment by sbmalik** [comment]
@dungx48 I've created a PR for the updated arcface-trt8 support
Kindly check: https://github.com/sbmalik/tensorrtx/tree/arcface-trt8/arcface

One thing to add, I ran the `python3 gen_wts.py` in the following **NVIDIA-Container**
`nvcr.io/nvidia/mxnet:22.04-py3 `
