### ISSUE TITLE
No module named 'kbds.util.fdfs_util' 

### ISSUE THREAD

**Issue by syedmustafa54** [zhouyuchong/face-recognition-deepstream#14]

**Comment by syedmustafa54** [comment]
Hello @zhouyuchong thanks for the new update, but getting the error no module
```
from kbds.util.fdfs_util.fdfs_util import FastDfsUtil
ModuleNotFoundError: No module named 'kbds.util.fdfs_util'
```

**Comment by qustions** [comment]
Hello @syedmustafa54 I think the problem is @zhouyuchong forgot to comment  [this line](https://github.com/zhouyuchong/face-recognition-deepstream/blob/main/src/kbds/app/face/face_data.py#L12)  comment that line and check the code.

**Comment by zhouyuchong** [comment]
@syedmustafa54 you can delete this line since there is no need to import this package. I'm using fastfdfs to upload images and npy files to server.
