### ISSUE TITLE
ERROR: [TRT]: 3: getPluginCreator could not find plugin: Decode_TRT version: 1

### ISSUE THREAD

**Issue by qustions** [zhouyuchong/face-recognition-deepstream#15]
Hello @zhouyuchong  I tried to run the latest code with latest infer-plugin installed getting this error. But I have the old version of the code that's unserialising the model but not the new code  
```
NvMultiObjectTracker] Initialized
0:00:06.060145189 151171 0x7fb1c8006100 WARN                 nvinfer gstnvinfer.cpp:680:gst_nvinfer_logger:<primary-inference> NvDsInferContext[UID 1]: Warning from NvDsInferContextImpl::initialize() <nvdsinfer_context_impl.cpp:1161> [UID = 1]: Warning, OpenCV has been deprecated. Using NMS for clustering instead of cv::groupRectangles with topK = 20 and NMS Threshold = 0.5

**PERF:  {'stream0': 0.0, 'stream1': 0.0, 'stream2': 0.0, 'stream3': 0.0, 'stream4': 0.0, 'stream5': 0.0, 'stream6': 0.0, 'stream7': 0.0, 'stream8': 0.0, 'stream9': 0.0, 'stream10': 0.0, 'stream11': 0.0, 'stream12': 0.0, 'stream13': 0.0, 'stream14': 0.0, 'stream15': 0.0} 

ERROR: [TRT]: 3: getPluginCreator could not find plugin: Decode_TRT version: 1
ERROR: [TRT]: 1: [pluginV2Runner.cpp::load::291] Error Code 1: Serialization (Serialization assertion creator failed.Cannot deserialize plugin since corresponding IPluginCreator not found in Plugin Registry)
ERROR: [TRT]: 4: [runtime.cpp::deserializeCudaEngine::75] Error Code 4: Internal Error (Engine deserialization failed.)
ERROR: Deserialize engine failed from file: /opt/nvidia/deepstream/deepstream-6.0/sources/apps/deepstream_python_apps/models/retinaface/retina_r50.engine
0:00:06.617339261 151171 0x7fb1c8006100 WARN                 nvinfer gstnvinfer.cpp:680:gst_nvinfer_logger:<primary-inference> NvDsInferContext[UID 1]: Warning from NvDsInferContextImpl::deserializeEngineAndBackend() <nvdsinfer_context_impl.cpp:1888> [UID = 1]: deserialize engine from file :/opt/nvidia/deepstream/deepstream-6.0/sources/apps/deepstream_python_apps/models/retinaface/retina_r50.engine failed
0:00:06.617380495 151171 0x7fb1c8006100 WARN                 nvinfer gstnvinfer.cpp:680:gst_nvinfer_logger:<primary-inference> NvDsInferContext[UID 1]: Warning from NvDsInferContextImpl::generateBackendContext() <nvdsinfer_context_impl.cpp:1993> [UID = 1]: deserialize backend context from engine from file :/opt/nvidia/deepstream/deepstream-6.0/sources/apps/deepstream_python_apps/models/retinaface/retina_r50.engine failed, try rebuild
0:00:06.617391388 151171 0x7fb1c8006100 INFO                 nvinfer gstnvinfer.cpp:683:gst_nvinfer_logger:<primary-inference> NvDsInferContext[UID 1]: Info from NvDsInferContextImpl::buildModel() <nvdsinfer_context_impl.cpp:1914> [UID = 1]: Trying to create engine from model files
ERROR: failed to build network since there is no model file matched.
ERROR: failed to build network.
0:00:06.618088857 151171 0x7fb1c8006100 ERROR                nvinfer gstnvinfer.cpp:677:gst_nvinfer_logger:<primary-inference> NvDsInferContext[UID 1]: Error in NvDsInferContextImpl::buildModel() <nvdsinfer_context_impl.cpp:1934> [UID = 1]: build engine file failed
0:00:06.618108014 151171 0x7fb1c8006100 ERROR                nvinfer gstnvinfer.cpp:677:gst_nvinfer_logger:<primary-inference> NvDsInferContext[UID 1]: Error in NvDsInferContextImpl::generateBackendContext() <nvdsinfer_context_impl.cpp:2020> [UID = 1]: build backend context failed
0:00:06.618118811 151171 0x7fb1c8006100 ERROR                nvinfer gstnvinfer.cpp:677:gst_nvinfer_logger:<primary-inference> NvDsInferContext[UID 1]: Error in NvDsInferContextImpl::initialize() <nvdsinfer_context_impl.cpp:1257> [UID = 1]: generate backend failed, check config file settings
0:00:06.618523031 151171 0x7fb1c8006100 WARN                 nvinfer gstnvinfer.cpp:883:gst_nvinfer_start:<primary-inference> error: Failed to create NvDsInferContext instance
0:00:06.618533300 151171 0x7fb1c8006100 WARN                 nvinfer gstnvinfer.cpp:883:gst_nvinfer_start:<primary-inference> error: Config file path: /opt/nvidia/deepstream/deepstream-6.0/sources/apps/deepstream_python_apps/apps/fr/face-recognition-deepstream/src/kbds/configs/face/config_retinaface.txt, NvDsInfer Error: NVDSINFER_CONFIG_FAILED
gst-resource-error-quark: Failed to create NvDsInferContext instance (1)
Traceback (most recent call last):
  File "/opt/nvidia/deepstream/deepstream-6.0/sources/apps/deepstream_python_apps/apps/fr/face-recognition-deepstream/test/../src/kbds/core/pipeline.py", line 122, in bus_call_abs
    search_index = search_index[0].split('-')[2][:-1]
TypeError: 'NoneType' object is not subscriptable
[NvMultiObjectTracker] De-initialized
(True, 'success')
src: <Stream task-0 task-0-Stream> 
source_bin: <__gi__.GstURIDecodeBin object at 0x7fb23ce07b80 (GstURIDecodeBin at 0x383a820)>
<enum GST_STATE_CHANGE_ASYNC of type Gst.StateChangeReturn>
gstname= video/x-raw
pad name:  sink_0
Decodebin linked to pipeline
gstname= audio/x-raw
gst-stream-error-quark: Internal data stream error. (1)
delete finished

```

**Comment by zhouyuchong** [comment]
@qustions seems that something wrong with trt version. If your engine file is generated in deepstream 6.0, please re-generate a new trt engine since 6.0 and 6.1 use different trt version.

**Comment by qustions** [comment]
@zhouyuchong I am using deeepstream6.0 does this code support deepstream6.0

**Comment by zhouyuchong** [comment]
> @zhouyuchong I am using deeepstream6.0 does this code support deepstream6.0

yes, but in **custom nvinfer**, you should delete [nvdspreprocess](https://github.com/zhouyuchong/gst-nvinfer-custom/blob/db9b96aad8e72038c3ffd400f0b7dbf339f444e9/Makefile#L28) and relevant codes. I'm wondering how could you compile **custom nvinfer** successfully before?

**Comment by qustions** [comment]
@zhouyuchong so you suggest to use deepstream6.1 then?

**Comment by zhouyuchong** [comment]
@Mangesh1996 
+ if you are using the **trt plan engine** file generated from `tensorrtx`, you should [preload](https://github.com/zhouyuchong/face-recognition-deepstream/blob/608c0c80975c85e978c2b7d121955ee033378589/src/kbds/app/face/face.py#L24) the decode plugin.
```
import ctypes
ctypes.cdll.LoadLibrary('/opt/models/retinaface/libplugin_rface.so')
```
+ make sure you are using the corresponding version tensorrt as your deepstream.

**Comment by Mangesh1996** [comment]
Your reply is great. However, I am ensuring that the version of TensorRT is the same and I execute every step on a local machine.
But not working

**Comment by zhouyuchong** [comment]
> .1.1 and tensorrt 8.4.2

can you give more details about this error?

**Comment by Mangesh1996** [comment]
Yes I can share logs file and config of retinaface 
[logs.txt](https://github.com/zhouyuchong/face-recognition-deepstream/files/11085742/logs.txt)
[config_retinaface.txt](https://github.com/zhouyuchong/face-recognition-deepstream/files/11085743/config_retinaface.txt)

**Comment by zhouyuchong** [comment]
@Mangesh1996 I guess there are some more logs before the first line you gave 
```
ERROR: ../nvdsinfer/nvdsinfer_model_builder.cpp:860 failed to build network since there is no model file matched
```
can you share them.

**Comment by zhouyuchong** [comment]
> ERROR: [TRT]: 1: [pluginV2Runner.cpp::load::293] Error Code 1: Serialization (Serialization assertion creator failed.Cannot deserialize plugin since corresponding IPluginCreator not found in Plugin Registry) ERROR: [TRT]: 4: [runtime.cpp::deserializeCudaEngine::50] Error Code 4: Internal Error (Engine deserialization failed.) ERROR: ../nvdsinfer/nvdsinfer_model_builder.cpp:1528 Deserialize engine failed from file: /home/easemyai/Documents/test/face-recognition-deepstream/models/retinaface/retina_r50.engine 0:00:08.246008419 62293 0x3888750 WARN nvinfer gstnvinfer.cpp:748:gst_nvinfer_logger: NvDsInferContext[UID 1]: Warning from NvDsInferContextImpl::deserializeEngineAndBackend() <nvdsinfer_context_impl.cpp:1897> [UID = 1]: deserialize engine from file :/home/easemyai/Documents/test/face-recognition-deepstream/models/retinaface/retina_r50.engine failed 0:00:08.247109063 62293 0x3888750 WARN nvinfer gstnvinfer.cpp:748:gst_nvinfer_logger: NvDsInferContext[UID 1]: Warning from NvDsInferContextImpl::generateBackendContext() <nvdsinfer_context_impl.cpp:2002> [UID = 1]: deserialize backend context from engine from file :/home/easemyai/Documents/test/face-recognition-deepstream/models/retinaface/retina_r50.engine failed, try rebuild 0:00:08.247139360 62293 0x3888750 INFO nvinfer gstnvinfer.cpp:751:gst_nvinfer_logger: NvDsInferContext[UID 1]: Info from NvDsInferContextImpl::buildModel() <nvdsinfer_context_impl.cpp:1923> [UID = 1]: Trying to create engine from model files ERROR: ../nvdsinfer/nvdsinfer_model_builder.cpp:860 failed to build network since there is no model file matched. ERROR: ../nvdsinfer/nvdsinfer_model_builder.cpp:799 failed to build network. 0:00:08.897701639 62293 0x3888750 ERROR nvinfer gstnvinfer.cpp:745:gst_nvinfer_logger: NvDsInferContext[UID 1]: Error in NvDsInferContextImpl::buildModel() <nvdsinfer_context_impl.cpp:1943> [UID = 1]: build engine file failed 0:00:08.898486930 62293 0x3888750 ERROR nvinfer gstnvinfer.cpp:745:gst_nvinfer_logger: NvDsInferContext[UID 1]: Error in NvDsInferContextImpl::generateBackendContext() <nvdsinfer_context_impl.cpp:2029> [UID = 1]: build backend context failed 0:00:08.898507025 62293 0x3888750 ERROR nvinfer gstnvinfer.cpp:745:gst_nvinfer_logger: NvDsInferContext[UID 1]: Error in NvDsInferContextImpl::initialize() <nvdsinfer_context_impl.cpp:1266> [UID = 1]: generate backend failed, check config file settings 0:00:08.898527711 62293 0x3888750 WARN nvinfer gstnvinfer.cpp:996:gst_nvinfer_start: error: Failed to create NvDsInferContext instance 0:00:08.898538086 62293 0x3888750 WARN nvinfer gstnvinfer.cpp:996:gst_nvinfer_start: error: Config file path: /home/easemyai/Documents/test/face-recognition-deepstream/src/kbds/configs/face/config_retinaface.txt, NvDsInfer Error: NVDSINFER_CONFIG_FAILED

Notice the first line 
```
Serialization assertion creator failed.Cannot deserialize plugin since corresponding IPluginCreator not found in Plugin Registry
```
as I mentioned [before](https://github.com/zhouyuchong/face-recognition-deepstream/issues/15#issuecomment-1484335322), if your trt file is generated from [tensorrtx](https://github.com/wang-xinyu/tensorrtx), you should preload its **plugin** .so file before serialization. 
try it out and let me know what's happening. :smile:
