### ISSUE TITLE
hi, I unable add your face landmarks(face-detect-deepstream) of you to this pipeline. Please, help me!

### ISSUE THREAD

**Issue by manhdoan291** [zhouyuchong/face-recognition-deepstream#16]
I tried to include the face landmarks that I asked you @zhouyuchong  before into this pipeline but it seems to have a data flow error that I can't fix at all.
I don't seem to see result_landmark[](result_landmark=None) return results when I add queue4.link(tgie)
    tgie.link(queue5)
    queue5.link(tiler)
    tiler.link(queue6)
[main.py.txt](https://github.com/zhouyuchong/face-recognition-deepstream/files/9828003/main.py.txt)
it even lost bounding box object when i set process-mode=2(get-current). How to fix these error ?
![Screenshot from 2022-10-20 15-53-16](https://user-images.githubusercontent.com/45356143/196903566-91831a30-e7d0-426a-85f7-fe59398c9ccf.png)

**Comment by manhdoan291** [comment]
my video when run: https://drive.google.com/file/d/1hzRvY99JFt6LxU3itwjMp0DetsjCMzuA/view?usp=sharing

**Comment by zhouyuchong** [comment]
@manhdoan291 It seems you are using codes in another repo. I've deleted **YOLOv5** from current pipeline since there are some problems in retrieving data in **process-mode=2**. 
However, if you don't need to extract face embedding but only to visualize detection and landmarks, you can refer to this [repo](https://github.com/zhouyuchong/retinaface-deepstream-python) which I test and modify today.

**Comment by manhdoan291** [comment]
@zhouyuchong I will remove yolov5 from this pipeline. I'm trying to combine face landmark with face-align + embedding but can't because of wrong pipeline. I don't know how to fix it

**Comment by zhouyuchong** [comment]
@manhdoan291 In this repo, you can't reach lmks in python codes because I retrieve these data in c++, **gst-nvinfer** source codes. Deepstream python only offers few APIs which can't satisfy alignment requirement.

**Comment by manhdoan291** [comment]
@zhouyuchong In fact I added the face-land mark here (https://github.com/zhouyuchong/face-detect-deepstream/blob/main/main.py) to add to this pipeline (because face-landmark shows up) pretty good). But I'm understanding you say custom-gst-nvinfer for face-align so the value of land-marks face() (result_landmark[]=None) is correct ?

**Comment by manhdoan291** [comment]
@zhouyuchong How to add lmks on this repo : https://github.com/manhdoan291/face-detect-deepstream to this repo https://github.com/manhdoan291/face-recognition-deepstream ?
This line https://github.com/manhdoan291/face-detect-deepstream/blob/main/main.py#L159 get result landmarks correct and it displays very well.

**Comment by manhdoan291** [comment]
@zhouyuchong  I realized all I can't display landmark is because of it :
if not tiler_sink_pad:
        sys.stderr.write(" Unable to get sink pad of tiler \n")
    else:
        i = 1
        tiler_sink_pad.add_probe(
            Gst.PadProbeType.BUFFER, osd_sink_pad_buffer_probe, 0)

    sgie_sink_pad = queue3.get_static_pad("sink")
    if not sgie_sink_pad:
        sys.stderr.write(" Unable to get sink pad of tiler \n")
    else:
        i = 3
        sgie_sink_pad.add_probe(Gst.PadProbeType.BUFFER,
                                sgie_sink_pad_buffer_probe, 0)

    osd_sink_pad = pgie.get_static_pad("sink")
    if not osd_sink_pad:
        sys.stderr.write(" Unable to get sink pad of osd \n")
    else:
        i = 2
        tiler_sink_pad.add_probe(Gst.PadProbeType.BUFFER,
                               tiler_sink_pad_buffer_probe, 0)
But after I added landmark face to this repo i get no result: print("get facial features of person {}".format(
                                    obj_meta.object_id))
even though I left process-mode = 2

**Comment by manhdoan291** [comment]
@zhouyuchong  
so is there any solution to approach lmks in this python code when retrieving these data in c++ source code, gst-nvinfer to embed faces?

**Comment by zhouyuchong** [comment]
> @zhouyuchong so is there any solution to approach lmks in this python code when retrieving these data in c++ source code, gst-nvinfer for embed faces?

What's your purpose to get landmarks in this repo? Since I use fakesink and drop faces once it's been infered by arcface. 

For you question, I think you can get those data the same way as before. Using a probe in python codes to get tensor-output.
