### ISSUE TITLE
ImportError: libpython3.6m.so.1.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by dungx48** [zhouyuchong/face-recognition-deepstream#19]
I try "sudo apt-get install libpython3.6" but it still doesnt work

**Comment by zhouyuchong** [comment]
@dungx48 sorry didn't met this problem before. It seems your system missing python3.6 environment.

**Comment by dungx48** [comment]
> 

@zhouyuchong i use miniconda python=3.6.9. What version of env python do you used ?

**Comment by zhouyuchong** [comment]
@dungx48 I use python 3.8 in Ubutu 20.04. As far as I know, deepstream python have some problem compiling with python 3.6.

**Comment by dungx48** [comment]
i also just tried on python 3.8 and it doesn't give this error. I'm having a problem in kafka because i'm not used to it, if I have problems I will refer to you later. thank you very much :+1:
