### ISSUE TITLE
libArcFaceDecoder.so is never used

### ISSUE THREAD

**Issue by willosonico** [zhouyuchong/face-recognition-deepstream#20]
i can't find any reference in the code of models/arcface/libArcFaceDecoder.so as provided in the google drive file [https://drive.google.com/drive/folders/1-Ma6qSnOx-XHMDYBLrpoclIoqlCT7Lsi](https://drive.google.com/drive/folders/1-Ma6qSnOx-XHMDYBLrpoclIoqlCT7Lsi), is that correct?

**Comment by zhouyuchong** [comment]
@willosonico yeah since arcface is not a detector and we set 
```
network-type=100
output-tensor-meta=1
```
we don't need this .so file to decode output of tensorrt.
