### ISSUE TITLE
[Question] File Missing (libplugin_rface.so) during Installation

### ISSUE THREAD

**Issue by cloudlakecho** [zhouyuchong/face-recognition-deepstream#21]
During installation, I couldn't find a related file, "libplugin_rface.so". 

Installation [step 2](https://github.com/zhouyuchong/face-recognition-deepstream#2---modify-all-path-in-config-and-codes)
&nbsp;&nbsp; Modify line 24 in src/kbds/app/face.py (actually src/kbdes/app/face/face.py)
&nbsp;&nbsp;  [related code line](https://github.com/zhouyuchong/face-recognition-deepstream/blob/main/src/kbds/app/face/face.py#L24)

I downloaded the pre trained weight and other files from [the Google Drive](https://drive.google.com/drive/folders/1HTdIhGrKP7JnKY6n8F95mI7SBnx7-4R3) in [Pre Trained section](https://github.com/zhouyuchong/face-recognition-deepstream#pretrained) in ReadMe, but the "libplogin_rface.so" isn't included. 

Where could I find the file? 

Or should I compile to generate the file at [the retinaface link](https://github.com/wang-xinyu/tensorrtx/tree/master/retinaface) in the ReadMe?

**Comment by zhouyuchong** [comment]
@cloudlakecho Yeah, it's a decode trt plugin generated by tensorrtx. Careful it should be bound with you trt file, .engine exactly. Since u said ur platform is arch_64, I suggest you to gen a new .engine model file step by step follow [tensorrtx](https://github.com/zhouyuchong/tensorrtx).

**Comment by cloudlakecho** [comment]
@zhouyuchong Thanks for the guide. 

I have two additional questions:
&nbsp;&nbsp; So instead of using ENGINE and SO files from the Google Drive, I have to generate them? 
&nbsp;&nbsp; The repository you shared looks like parents directory of [retinaface](https://github.com/wang-xinyu/tensorrtx/tree/master/retinaface) and [arcface](https://github.com/wang-xinyu/tensorrtx/tree/master/arcface) in ReadMe. Could I use these two repositories to generate files? 
&nbsp;&nbsp;&nbsp;&nbsp; Though [arcface](https://github.com/zhouyuchong/tensorrtx/tree/master/retinaface) link in your TensorRTx and ReadMe looks different.

**Comment by zhouyuchong** [comment]
@cloudlakecho yes, you better generate them since as my test before, trt file generated on different gpu device can't be compatibility with others.

I modifyed arcface compile codes based on original *tensorrtx* repo so it can compile successfully. The original one's tensorrt version is too old.

**Comment by cloudlakecho** [comment]
@zhouyuchong Thanks for explanation. I will try to generate ENGINE, SO and others from the link.
