### ISSUE TITLE
[Question] Frame per Second (FPS) Becomes Zero, **PERF:  {'stream0': 0.0} 

### ISSUE THREAD

**Issue by cloudlakecho** [zhouyuchong/face-recognition-deepstream#23]
Hello;

I am running the test code, ["face_test_demo.py"](https://github.com/zhouyuchong/face-recognition-deepstream#4---start-app).  It looks like executing all pipeline components (including Kafka) but my frame rate suddenly becomes zero. 

Here is runtime screen when it happened ( [entire runtime screen - readable by Chrome Browser](https://drive.google.com/file/d/1w5F7JcaAvIs_qahTUhQxXim1_QvZXk_t/view?usp=sharing) ): 
```
.
.
.
:00:43.000497888 15720      0x1ffa0a0 INFO                 nvinfer gstnvinfer.cpp:646:gst_nvinfer_logger:<primary-inference> NvDsInferContext[UID 1]: Info from NvDsInferContextImpl::generateBackendContext() <nvdsinfer_context_impl.cpp:2012> [UID = 1]: Use deserialized engine model: /home/isi/pre_trained/arm/retina_r50.engine
0:00:43.004738880 15720      0x1ffa0a0 INFO                 nvinfer gstnvinfer_impl.cpp:328:notifyLoadModelStatus:<primary-inference> [UID 1]: Load new model:/home/isi/project/face-recognition-deepstream/src/kbds/configs/face/config_retinaface.txt sucessfully
(True, 'success')
src: <Stream task-5 task-5-Stream> 
source_bin: <__gi__.GstURIDecodeBin object at 0xffff461d78c0 (GstURIDecodeBin at 0xfffdb4018f00)>
<enum GST_STATE_CHANGE_SUCCESS of type Gst.StateChangeReturn>
Opening in BLOCKING MODE 
NvMMLiteOpen : Block : BlockType = 279 
NVMEDIA: Reading vendor.tegra.display-size : status: 6 
NvMMLiteBlockCreate : Block : BlockType = 279 
gstname= video/x-raw
pad name:  sink_0
/home/isi/project/face-recognition-deepstream/test/../src/kbds/core/pipeline.py:491: Warning: g_hash_table_lookup: assertion 'hash_table != NULL' failed
  sinkpad = self.streammux.get_request_pad(pad_name)
/home/isi/project/face-recognition-deepstream/test/../src/kbds/core/pipeline.py:491: Warning: g_hash_table_insert_internal: assertion 'hash_table != NULL' failed
  sinkpad = self.streammux.get_request_pad(pad_name)
Decodebin linked to pipeline

**PERF:  {'stream0': 14.8} 

======== delete src test =======
[NvMultiObjectTracker] De-initialized
delete finished

**PERF:  {'stream0': 14.79} 


**PERF:  {'stream0': 0.0} 


**PERF:  {'stream0': 0.0} 
```

I was suspicious of the bandwidth limit in my network, so I reduced image width and height in "face.py" code ([code line](https://github.com/zhouyuchong/face-recognition-deepstream/blob/main/src/kbds/app/face/face.py#L41-L45), but the situation is persitsance. And the image nor NPY file made. 

I also see the warning of "Warning: g_hash_table_insert_internal: assertion 'hash_table != NULL' **failed**". If this is main cause how could I fix it? [The code line](https://github.com/zhouyuchong/face-recognition-deepstream/blob/main/src/kbds/core/pipeline.py#L477) doesn't indicate where the Hash Table existed.

What could be issues? Any suggestion appreciated.    

Thank You. 

Runtime Environment:
&nbsp;&nbsp; OS: Ubuntu 20.04 in AArch 64
&nbsp;&nbsp; DeepStream 6.1 with Python 3.8
&nbsp;&nbsp; Nivida Orin

**Comment by zhouyuchong** [comment]
@cloudlakecho The outputs are correct.
the [face_test_demo.py](https://github.com/zhouyuchong/face-recognition-deepstream/blob/main/test/face_test_demo.py) demos below functions:
+ add a src named task-0
+ add a src named task-5
+ get status of task-5 and task-111
+ delete src/task-0
+ delete src/task-5 ( pipeline will be set NULL since there is no source in pipeline)
+ add a src named task-5 (pipeline will be reinited)
+ delete src/task-5

So there will not be any source in pipeline after all.

**Comment by cloudlakecho** [comment]
@zhouyuchong Thanks for detailed explanation on the code. 
So my understanding, if your input RTSP is a network camera, the person face should be in the camera view before "delete src/task-0" step?

**Comment by zhouyuchong** [comment]
@cloudlakecho this steps are intended to demo how to add/delete/get sources at runtime, just some basic operations not related to face recog.

**Comment by cloudlakecho** [comment]
@zhouyuchong Thanks for the answers for overall process. 

Regarding the "not related face recog", is this related to add and delete functions, right? 

I notice that the output of ["face_test_demo.py"](https://github.com/zhouyuchong/face-recognition-deepstream#4---start-app) is [the image of face(s)](https://github.com/zhouyuchong/face-recognition-deepstream#5---check-result). Is the face detection and recognition performed at the task-5?

**Comment by zhouyuchong** [comment]
> @zhouyuchong Thanks for the answers for overall process.
> 
> Regarding the "not related face recog", is this related to add and delete functions, right?
> 
> I notice that the output of ["face_test_demo.py"](https://github.com/zhouyuchong/face-recognition-deepstream#4---start-app) is [the image of face(s)](https://github.com/zhouyuchong/face-recognition-deepstream#5---check-result). Is the face detection and recognition performed at [the task-5](https://github.com/zhouyuchong/face-recognition-deepstream/blob/608c0c80975c85e978c2b7d121955ee033378589/test/face_test_demo.py#L27)?
> 
>    I am mentioning these lines in the code:
> 
> ```
> from kbds.app import DSFace
> from kbds import Stream
> 
> app = DSFace("localhost;9092;deepstream")
> print(app.start())
> 
> str_id = "task-{}".format(id)
> src = Stream(str_id, "file:///media/test.ts")
> print(app.add_src(src))
> app.play_src(str_id)
> ```

For Q1, yes, they are functions about pipeline.
For Q2, the output images will be saved, you can find them in this [path](https://github.com/zhouyuchong/face-recognition-deepstream/blob/608c0c80975c85e978c2b7d121955ee033378589/src/kbds/app/face/face_data.py#L147). face detection and recognition will be performed in *every* task added to pipeline.

**Comment by cloudlakecho** [comment]
@zhouyuchong Thanks for the answer, especially "face detection and recognition will be performed in every task added to pipeline."
