### ISSUE TITLE
What does FaceState mean?

### ISSUE THREAD

**Issue by akhil-faceintel** [zhouyuchong/face-recognition-deepstream#25]
Great work! 

Can you elaborate what does State<num> means here? 

@unique
class FaceState(Enum):
    Init = 0
    State1 = 1
    State2 = 2
    State3 = 3
    State4 = 4

**Comment by zhouyuchong** [comment]
@akhil-faceintel sry didn't maintain this repo for a long time. 
+ Init: default state
+ State1: a 'FaceFeature' object without embedding
+ State2: a 'FaceFeature' object with embedding, images not saved
+ State3: all ready to send by kafka
+ State4: a finished face

**Comment by akhil-faceintel** [comment]
Thanks for explaining the states @zhouyuchong. 

I have another question regarding user_meta information. Can you please explain how you add obj_user_meta_list information in obj_meta. 

What does tensor_meta has to get the face embeddings? 

![image](https://github.com/zhouyuchong/face-recognition-deepstream/assets/130441911/b42dd201-a505-42e6-be7d-b5b7de809d52)

**Comment by akhil-faceintel** [comment]
Thanks for the explanation @zhouyuchong.
