### ISSUE TITLE
OSError: /opt/models/retinaface/libplugin_rface.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by shaluashraf** [zhouyuchong/face-recognition-deepstream#28]
Am trying this repo, but facing issue in line 24 in src/kbds/app/face.py
How to solve it?

**Comment by zhouyuchong** [comment]
@shaluashraf this line loads decoder file for model file generated by tensorrtx. If you follow every steps in tensorrtx repo, you should find a file named "libdecodeplugin.so". that's the one you should load before init the model.
