### ISSUE TITLE
how do we feed in an face image to search through video?

### ISSUE THREAD

**Issue by Athuliva** [zhouyuchong/face-recognition-deepstream#29]

**Comment by zhouyuchong** [comment]
@Athuliva I'm not sure what you mean by "search through video", however, you can calculate cos similarity in probe once a face detected.

**Comment by Athuliva** [comment]
do you have a code to generate embedding of a face from an image? i used the code in  [arcface-r100.cpp](https://github.com/wang-xinyu/tensorrtx/blob/master/arcface/arcface-r100.cpp). Both codes uses the same engine file, but for the same images it gave different results

**Comment by zhouyuchong** [comment]
@Athuliva theoretically their outputs should be the same. please check your preprocess function.
