### ISSUE TITLE
Arcface inference results in l_user_meta (of "obj_user_meta_list") always 'None'

### ISSUE THREAD

**Issue by varunvv** [zhouyuchong/face-recognition-deepstream#31]
Hi,
I am using deepstream 6.3 for running the source code. 
From the logs I could understand that model loading and inference are working, however the inference result from arcface model that is supposed to be in the variable "l_user_meta" is always "None".

The warning that I am getting are given below
![Screenshot from 2024-02-23 16-37-51](https://github.com/zhouyuchong/face-recognition-deepstream/assets/16333208/3660f1a7-15b5-40cc-8301-1544ce359aa1)

I have wrote some log statements in the code to see the value of "l_user_meta" as shown below 
![Screenshot from 2024-02-23 16-38-27](https://github.com/zhouyuchong/face-recognition-deepstream/assets/16333208/6938f528-9096-4e6e-b279-97ecf22eaf12)

The log file content is given below 
`INFO: ../nvdsinfer/nvdsinfer_model_builder.cpp:610 [Implicit Engine Info]: layers num: 2
0   INPUT  kFLOAT data            3x112x112       
1   OUTPUT kFLOAT prob            512x1x1         

gstnvtracker: Loading low-level lib at /app/default_tracker_63/libnvds_nvmultiobjecttracker_63.so
[NvMultiObjectTracker] Initialized
INFO: ../nvdsinfer/nvdsinfer_model_builder.cpp:610 [Implicit Engine Info]: layers num: 2
0   INPUT  kFLOAT data            3x480x640       
1   OUTPUT kFLOAT prob            189001x1x1      

[NvMultiObjectTracker] De-initialized
INFO: ../nvdsinfer/nvdsinfer_model_builder.cpp:610 [Implicit Engine Info]: layers num: 2
0   INPUT  kFLOAT data            3x112x112       
1   OUTPUT kFLOAT prob            512x1x1         

gstnvtracker: Loading low-level lib at /app/default_tracker_63/libnvds_nvmultiobjecttracker.so
[NvMultiObjectTracker] Initialized
INFO: ../nvdsinfer/nvdsinfer_model_builder.cpp:610 [Implicit Engine Info]: layers num: 2
0   INPUT  kFLOAT data            3x480x640       
1   OUTPUT kFLOAT prob            189001x1x1      

[NvMultiObjectTracker] De-initialized
--------- start app
localhost;9092;deepstream
(True, 'success, state <enum GST_STATE_CHANGE_SUCCESS of type Gst.StateChangeReturn>')

-----------------------------------------------------------------------------
set index of src task-0 to 0
add set return : <enum GST_STATE_CHANGE_ASYNC of type Gst.StateChangeReturn>
Starting pipeline 

Warning: gst-library-error-quark: NvInfer output-tensor-meta is enabled but init_params auto increase memory (auto-inc-mem) is disabled. The bufferpool will not be automatically resized. (5): gstnvinfer.cpp(887): gst_nvinfer_start (): /GstPipeline:pipeline0/GstNvInfer:secondary-nvinference-engine

Warning: gst-library-error-quark: NvInfer output-tensor-meta is enabled but init_params auto increase memory (auto-inc-mem) is disabled. The bufferpool will not be automatically resized. (5): gstnvinfer.cpp(887): gst_nvinfer_start (): /GstPipeline:pipeline0/GstNvInfer:primary-inference

**PERF:  {'stream0': 0.0} 

(True, 'success')
gstname= video/x-raw
pad name:  sink_0
Decodebin linked to pipeline
src: <Stream task-0 task-0-Stream> 
source_bin: <__gi__.GstURIDecodeBin object at 0x7f498795c380 (GstURIDecodeBin at 0x26b87d0)>
<enum GST_STATE_CHANGE_SUCCESS of type Gst.StateChangeReturn>

**PERF:  {'stream0': 0.0} 

set index of src task-5 to 1
add set return : <enum GST_STATE_CHANGE_FAILURE of type Gst.StateChangeReturn>
error, source state change failure
(True, 'success')
src: <Stream task-5 task-5-Stream> 
source_bin: <__gi__.GstURIDecodeBin object at 0x7f49879601c0 (GstURIDecodeBin at 0x26b8c90)>
<enum GST_STATE_CHANGE_FAILURE of type Gst.StateChangeReturn>
delete finished
id: task-5,  error: gst-resource-error-quark: Resource not found. (3), delete.
Log : ------------Inside sgie_sink_pad_buffer_probe------------
Log : ------------Inside sgie_sink_pad_buffer_probe------------
Log : ------------Inside sgie_sink_pad_buffer_probe------------
detect face-1 with resolution 40x49
detect face-0 with resolution 18x24
Log : ------------Inside sgie_sink_pad_buffer_probe------------
Log -----------------l_user_meta =  None
Log -----------------l_user_meta =  None
id: None encounters error: gst-core-error-quark: GStreamer error: state change failed and some element failed to post a proper error message with the reason for the failure. (4), delete.

**PERF:  {'stream0': 3.37} 

get status of task-5:  (False, 'source id(task-5) not exist', None)
get status of task-1111:  (False, 'source id(task-1111) not exist', None)

**PERF:  {'stream0': 0.0} 

======== delete src test =======
delete finished

**PERF:  {'stream0': 0.0} 

======== delete src test =======

**PERF:  {'stream0': 0.0} 

set index of src task-5 to 0
add set return : <enum GST_STATE_CHANGE_FAILURE of type Gst.StateChangeReturn>
error, source state change failure
Starting pipeline 

Warning: gst-library-error-quark: NvInfer output-tensor-meta is enabled but init_params auto increase memory (auto-inc-mem) is disabled. The bufferpool will not be automatically resized. (5): gstnvinfer.cpp(887): gst_nvinfer_start (): /GstPipeline:pipeline0/GstNvInfer:secondary-nvinference-engine

Warning: gst-library-error-quark: NvInfer output-tensor-meta is enabled but init_params auto increase memory (auto-inc-mem) is disabled. The bufferpool will not be automatically resized. (5): gstnvinfer.cpp(887): gst_nvinfer_start (): /GstPipeline:pipeline0/GstNvInfer:primary-inference

**PERF:  {'stream0': 0.0} 

(True, 'success')
src: <Stream task-5 task-5-Stream> 
source_bin: <__gi__.GstURIDecodeBin object at 0x7f498795cec0 (GstURIDecodeBin at 0x26b9150)>
<enum GST_STATE_CHANGE_FAILURE of type Gst.StateChangeReturn>
delete finished
id: task-5,  error: gst-resource-error-quark: Resource not found. (3), delete.

**PERF:  {'stream0': 0.0} 

======== delete src test =======

**PERF:  {'stream0': 0.0} 

**PERF:  {'stream0': 0.0} 

**PERF:  {'stream0': 0.0} 

**PERF:  {'stream0': 0.0} 

**PERF:  {'stream0': 0.0} 

**PERF:  {'stream0': 0.0} 

**PERF:  {'stream0': 0.0} 

**PERF:  {'stream0': 0.0} 

**PERF:  {'stream0': 0.0} 

**PERF:  {'stream0': 0.0} 

**PERF:  {'stream0': 0.0} 

**PERF:  {'stream0': 0.0} 

**PERF:  {'stream0': 0.0} 

**PERF:  {'stream0': 0.0} 

**PERF:  {'stream0': 0.0} 

`
All the the steps mentioned are followed with only difference in deepstream version, I am using 6.3.
could that be the issue?? Please help

**Comment by zhouyuchong** [comment]
@varunvv I've checked the warning and found [this](https://forums.developer.nvidia.com/t/incorrect-warning-message-when-output-tensor-meta-is-set-in-deepstream-6-3/263627) on the forum. Seems it is a bug but they've fixed in 6.4.

From logs you give I notice the all faces detected are small. You can modify the [min-input](https://github.com/zhouyuchong/face-recognition-deepstream/blob/608c0c80975c85e978c2b7d121955ee033378589/src/kbds/configs/face/config_arcface.txt#L73) size if you want arcface to infer on them. However, a small face may not have a good quality to get feature.
