### ISSUE TITLE
cannot find PGIE and SGIE config files in the repo

### ISSUE THREAD

**Issue by ahmedmuzammilAI** [zhouyuchong/face-recognition-deepstream#32]
Hi @zhouyuchong 

PGIE_CONFIG_FILE = os.path.join(sysp.cfg_path, APP_NAME, "config_retinaface.txt")
SGIE_CONFIG_FILE = os.path.join(sysp.cfg_path, APP_NAME, "config_arcface.txt")

I cannot find these config files in the repo can u please help me find them or upload them if they do not exist. I was trying to implement this in python and these would be of great help.
Thanks in advance.

**Comment by zhouyuchong** [comment]
@ahmedmuzammilAI [here](https://github.com/zhouyuchong/face-recognition-deepstream/tree/main/src/kbds/configs/face) they are. This repo hasn't been updated for a long time, sorry for all the mistakes. :sob:

**Comment by zhouyuchong** [comment]
@ahmedmuzammilAI BTW, if you want use do alignment before recog, please use the the [old version](https://github.com/zhouyuchong/gst-nvinfer-custom/tree/oldVersion) since I didn't modify this repo after update `nvinfer-custom`.
