### ISSUE TITLE
does arcface  used in this repo support multi- batching?

### ISSUE THREAD

**Issue by Athuliva** [zhouyuchong/face-recognition-deepstream#37]
i build a model with 
```
#define BATCH_SIZE 5 // currently, only support BATCH=1
```
since they have mention 'currently, only support BATCH=1', i am not sure how it works internally inside deepstream. One thing I noticed is that   if i set the batch size property greater than 2 `sgie.set_property("batch-size", 3)` it doesn't save the cropped and aligned images

**Comment by zhouyuchong** [comment]
@Athuliva `batch-size` of secondary gened infer engine is not a factor as I test so far. Unlike pgie, whose `batch-size` is strictly restricted to be the same of input-source number. Input to pgie will be batched in previous `Nvstreammux`, so they must be the same. 

If you check the source [code](https://github.com/zhouyuchong/gst-nvinfer-custom/blob/001d04eed481bab9fc5bf2673599cb69d8a5234f/gst-nvinfer/gstnvinfer.cpp#L2155), the sgie's input-batch is pushed once reaches sgie's max batchsize. 

If you want to dive into, you can debug the codes I mentioned above and see how it goes.

**Comment by zhouyuchong** [comment]
@Athuliva I add some new features including multi-batch support to `gst-nvinfer-custom`[https://github.com/zhouyuchong/gst-nvinfer-custom], have a try and inform me if there is any problem. :smile_cat:
